"""empty message

Revision ID: 201a451cfb46
Revises: d138b2f3aa44
Create Date: 2025-09-28 22:27:38.682175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '201a451cfb46'
down_revision = 'd138b2f3aa44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_history')
    op.drop_table('students')
    with op.batch_alter_table('login', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=300),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    op.create_table('students',
    sa.Column('enrollment_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('credits', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('percentage', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('enrollment_no', name=op.f('students_pkey'))
    )
    op.create_table('verification_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('degree', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('institution', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['login.email'], name=op.f('verification_history_user_email_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('verification_history_pkey'))
    )
    # ### end Alembic commands ###
